<?php 
$options = Zend_Controller_Front::getInstance()->getParam('bootstrap')->getOption('bootstrap');
$resultset = $this->resultset; 
?>

<script>
function HierarchyMenuDelete(hmid)
{
   if(hmid) {
    window.location.href='admin/cms/delete-menu/id/'+hmid;
   } else {
       window.location.href='admin/cms/managemenu';
   }
}
</script>

<!--<link rel="stylesheet" type="text/css" href="//code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
<link rel="stylesheet" type="text/css" href="lib/bootstrap/css/jquery.dataTables.css">
<script type="text/javascript" language="javascript" src="lib/jquery.js"></script>
<script type="text/javascript" language="javascript" src="lib/jquery.dataTables.js"></script>
<script type="text/javascript" language="javascript" src=
"lib/dataTables.jqueryui.js"></script>
<script type="text/javascript" language="javascript">
$(document).ready(function() {
  $('#example').dataTable({
      aLengthMenu: [[25, 50, 100, 150, -1], [25, 50, 100, 150, "All"]],    
      
  });
} );
</script>-->

<div class="content">
        
<div class="header">
    <h1 class="page-title">Testimonial List</h1>
</div>

<ul class="breadcrumb">
    <li><a href="<?php echo $options['siteUrl'];?>admin/dashboard/index">Home</a> <span class="divider">/</span></li>
    <li class="active">Manage <span class="divider">/</span></li>
    <li><a href="<?php echo $options['siteUrl'];?>admin/testimonial/edittestimonial">Add Testimonial</a> </li>
</ul>

<div class="container-fluid">
    <div class="row-fluid">
                       <div class="col-md-12">
    <?php if (count($this->messages)) { ?>
     <div class="alert alert-success" >
         <button data-dismiss="alert" class="close" type="button">x</button>
         <?php foreach ($this->messages as $message) {  ?>
         <?php echo $this->escape($message); ?>
         <?php } ?>
     </div>
    <?php } ?>
</div> 
        <div class="well">
    
                <table id="tt" class="easyui-datagrid" style="width:100%;" url="admin/testimonial/index"
                       iconCls="icon-save" toolbar="#tb" rownumbers="true" pagination="true" fitColumns="true" view="scrollview" nowrap="false" >
                    <thead>
                        <tr>
                            <th field="name" data-options="width:150">Name</th>
                            <th field="email" data-options="width:150">Email</th>
                            <th field="mobile" data-options="width:100">Mobile</th>
                            <th field="star_rating" data-options="width:100">Rating</th>
                            <th data-options="field:'Image',width:50,align:'center',formatter:formatImageAction">Image</th>
                            <th field="IsFeatured" data-options="width:100,align:'center',formatter:formatStatusAction">Display On Home Page</th>
                           <th data-options="field:'firma1',width:80,align:'center',formatter:formatTestimonialAction">Action</th>
                             </tr>
                    </thead>
                </table>
                <div id="tb" style="padding:3px;">
                    <span>Name</span>
                    <input id="name" onkeyup="doSearch()" style="line-height:26px;border: 1px solid #ccc">&nbsp;&nbsp;&nbsp;
                </div>
             
   </div>
<!--<div class="well">
    <table class="table display" id="example">
      <thead>
        <tr>
          <th>S.No.</th>
          <th>Name</th>
          <th>Email</th>
          <th>Mobile</th>
          <th>Rating</th>
          <th>Message</th>
          <th>Image</th>
          <th>Display On Home Page</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <?php
        if(count($resultset) >0) {
            foreach($resultset as $key=>$val){ ?>
        <tr>
          <td><?php echo $key+1;?></td>
          <td><?php echo $val['name'];?></td>
          <td><?php echo $val['email'];?></td>
          <td><?php echo $val['mobile'];?></td>
          <td><?php echo $val['star_rating'];?></td>
          <td><?php echo substr($val['message'],0,50);?>..</td>
          <td>
              <?php if(isset($val['Image']) && !empty($val['Image'])){
                  ?>
              <img src="<?php echo $baseUrl;?>public/upload/testimonial/<?php echo $val['Image'];?>" border="0" alt="image" width="100" height="100" />
             <?php }else{ ?>
              
              <img src="<?php echo $baseUrl;?>public/images/icon-package.jpg" border="0" alt="No image"  width="100" />
             <?php }?>
          </td>
          <td>
              <input type="checkbox" <?php echo !empty($val['IsFeatured']) && $val['IsFeatured'] ==1?'checked="checked"':''?> onClick="Active('<?php echo $val['id']?>');" id="Active_<?php echo $val['id']?>" name="Active" value="1">
          </td>
          <td>
              <a href="<?php echo $options['siteUrl'];?>admin/testimonial/edittestimonial/id/<?php echo $val['id'];?>" title="Edit"><i class="icon-pencil"></i></a>
              
              <a href="<?php echo $options['siteUrl'];?>admin/testimonial/deletetesti/id/<?php echo $val['id'];?>" class="Delete" title="Delete"><i class="icon-trash"></i></a>
          </td>
          
        </tr>
        <?php }
        }
        else {
        ?>
        <tr>
          <td colspan="6">No data found.</td>
        </tr>
        <?php } ?>
        
      </tbody>
    </table>
</div>-->

          
   </div>
</div>
</div>
<script type="text/javascript">
    function doSearch(){
        $('#tt').datagrid('load',{
            name: $('#name').val(),
          
        });
    }
    function formatTestimonialAction(val,row){
    var href = 'admin/testimonial/edittestimonial/id/'+row.id;
    var hrefDel = 'admin/testimonial/deletetesti/id/' + row.id;
//    var hrefDel = row.TravId;

        return '<a href="' + href + '" title="Edit"><i class="icon-pencil"></i></a> &nbsp; <a href="' + hrefDel + '" class="Delete" onclick="return confirm(\'Are you sure you want to delete?\')" title="Delete"><i class="icon-trash"></i></a>';
    } 
    
function formatImageAction(val, row) {
    var Image = row.Image;
//    alert(Image);
    if (Image !== "") {
        var str = row.Image;
        var exploded = str.split(',');

        return '<img src="public/upload/testimonial/'+Image+'"style="width:40;">';
    }
    else {
        return '<img src="public/images/no-image.jpg" style="width:40;">';
    }
}
function formatStatusAction(val, row) {
                            if (val != "" && val == 1) {
                                var checked = "checked";
                            }
                            else {
                                var checked = "";
                            }
                            return '<input type="checkbox" ' + checked + ' onClick="Active(\'' + row.id + '\')" id="Active_' + row.id + '" name="Active" value="1">';

                        }

</script>  
<script>

        function Active(a){ 
          
	var ele = $('#Active_'+a).prop("checked");
        if($('#Active_'+a).prop("checked") == true){
		var values = 1;
		$('#rate_'+a).addClass("hide");
	}else if($('#Active_'+a).prop("checked") == false){
		var values = 0;
		$('#rate_'+a).removeClass("hide");
	}
	//alert(values); return false;
        $.ajax({
		url:'<?php echo $options['siteUrl'];?>admin/testimonial/active/id/'+a+'/val/'+values,
		type:'POST',
		dataType:'json',
		success:function(result){
			if(result.status){
				alert('Record Update successfully.');
			}
//                        else{
//                            if(result.message==='Limit Exceed!!'){
//                                alert(result.message);
//                                $('#Active_'+a).prop("checked",false);
//                                
//                            }
//			
//			}
		},
		error:function(result){
			alert('Execution error activation!!');
		}
	});
	
}

</script> 
