<?php 
$options = Zend_Controller_Front::getInstance()->getParam('bootstrap')->getOption('bootstrap');
?>
<style type="text/css">
    li{list-style:none; color:#ed3237; font-size:13px;}
    ul{margin:0px; padding:0px;}
</style>
<?php
echo $this->headScript()->prependFile($options['siteUrl'].'public/fckeditor/fckeditor.js',$type='text/javascript'); ?>
<script type="text/javascript">
window.onload = function()
{
    if(document.getElementById('page_description')) {
        var oFCKeditor = new FCKeditor('page_description') ;
        oFCKeditor.BasePath = "public/fckeditor/" ;
        oFCKeditor.Height = 400;
        oFCKeditor.Width = 600; 
        oFCKeditor.ReplaceTextarea();
    }
}
</script>

<div class="content">
        
<div class="header">
    <h1 class="page-title">Edit Footer Page</h1>
</div>

<ul class="breadcrumb">
    <li><a href="<?php echo $options['siteUrl'];?>admin/dashboard/index">Home</a> <span class="divider">/</span></li>
    <li><a href="<?php echo $options['siteUrl'];?>admin/footer/index">Manage Footer Links</a> <span class="divider">/</span></li>
    <li class="active">Edit Footer Links</li>
</ul>

<div class="container-fluid">
    <div class="row-fluid">       
   
    <?php if($this->successMessage) { ?>
        <div class="alert alert-info">
        <button data-dismiss="alert" class="close" type="button">×</button>
        <?php echo $this->successMessage; ?>
        </div> 
    <?php } ?>
        
   <?php if($this->errorMessage) { ?>
       <div class="alert alert-error">
           <button data-dismiss="alert" class="close" type="button">×</button>
           <?php echo $this->errorMessage; ?>
       </div>
   <?php } ?>
      
   <?php if($this->error1Message) { ?>
       <div class="alert alert-error">
           <button data-dismiss="alert" class="close" type="button">×</button>
           <?php echo $this->error1Message; ?>
       </div>
   <?php } ?>   
        
<div class="well">
    <ul class="nav nav-tabs">
      <li class="active"><a href="#edit_page" data-toggle="tab">Edit Footer Page</a></li>
    </ul>
     <?php $form = $this->form;?>
    <div id="myTabContent" class="tab-content">
      <div class="tab-pane active in" id="add_page">
          <form id="add_page" class="edit_footer" method="<?php echo $this->form->getMethod();?>" action="<?php echo $this->form->getAction();?>" name="<?php echo $this->form->getName();?>" enctype="multipart/form-data">
        <?php echo $form->id;?>
         
        <label>Column Number</label>
        <?php echo $form->column_number;?>
        
        <label>Name</label>
        <?php echo $form->name;?>
       
        <label>Link</label>
        <?php echo $form->link;?>
        
        <?php echo $form->prelink;?>
        
        
        
         <label>Status</label>
        <?php echo $form->status_number;?>
        
        <div style="padding-top:20px;">
            <input type="submit" name="save" value="Save" class="btn btn-primary">
            <button class="btn btn-primary" type="button" onclick="window.location.href='admin/footer/index'">Cancel</button>
        </div>
        
    </form>
      </div>
  </div>

</div>                    
    </div>
</div>
</div>

<script>

    $(document).ready(function() {
        if($('#column_number').val()==6){
            $('#link').hide() && $('#prelink').show();
        }
        $( ".edit_footer" ).on('submit',function(){
            
            if($('#column_number').val()==6){
                $('#link').val($('#prelink').val());
            }
            
            if($('.edit_footer input[name="name"]').val().trim() == ''){
                $('.msg').html('Please enter name');
		$('.edit_footer input[name="name"]').focus();return false;
            }
            if($('.edit_footer input[name="link"]').val().trim() == ''){
                $('.msg').html('Please enter link above');
		$('.edit_footer input[name="link"]').focus();return false;
            }
            
            if($('.edit_footer select[name="column_number"]').val().trim() == ''){
                $('.msg').html('Please enter column number above');
		$('.edit_footer select[name="column_number"]').focus();return false;
            }
            
            //alert(data);
        });
        $("#column_number").on('click',function(){
            if($('#column_number').val()==6){
                $('#link').hide() && $('#prelink').show();
                  ;
            }
            else{
                $('#link').show() && $('#prelink').hide();
            }
        });
    });
</script>