<?php 
$options = Zend_Controller_Front::getInstance()->getParam('bootstrap')->getOption('bootstrap');
//echo "<pre>";print_r($options);die;
?>
<style type="text/css">
    li{list-style:none; color:#ed3237; font-size:13px;}
    ul{margin:0px; padding:0px;}
</style>


<div class="content">        
<div class="header">
    <h1 class="page-title">Add Blog</h1>
</div>

<ul class="breadcrumb">
    <li><a href="<?php echo $options['siteUrl'];?>admin/dashboard/index">Home</a> <span class="divider">/</span></li>
    <li><a href="<?php echo $options['siteUrl'];?>admin/travelogues/index">Manage Blog</a> <span class="divider">/</span></li>
    <li class="active">Add Blog</li>
</ul>

<div class="container-fluid">
    <div class="row-fluid">       
   
    <?php if($this->successMessage) { ?>
        <div class="alert alert-info">
        <button data-dismiss="alert" class="close" type="button">×</button>
        <?php echo $this->successMessage; ?>
        </div> 
    <?php } ?>
        
   <?php if($this->errorMessage) { ?>
       <div class="alert alert-error">
           <button data-dismiss="alert" class="close" type="button">×</button>
           <?php echo $this->errorMessage; ?>
       </div>
   <?php } ?>
      
   <?php if($this->error1Message) { ?>
       <div class="alert alert-error">
           <button data-dismiss="alert" class="close" type="button">×</button>
           <?php echo $this->error1Message; ?>
       </div>
   <?php } ?>   
        
<div class="well">
    <ul class="nav nav-tabs">
      <li class="active"><a href="#edit_page" data-toggle="tab">Add Blog</a></li>
    </ul>
     <?php $form = $this->form;?>
    <div id="myTabContent" class="tab-content">
      <div class="tab-pane active in" id="add_page">
    <form id="add_travelogues" class="add_travelogues" method="<?php echo $this->form->getMethod();?>" action="<?php echo $this->form->getAction();?>" name="<?php echo $this->form->getName();?>" enctype="multipart/form-data">
        <?php echo $form->TravId;?>
         
        <label style="padding-top:10px;">Blog Title <span style="font-size:12px;color:red;">*</span></label>
        <?php echo $form->TravTitle;?>
        
        <label style="padding-top:5px;">Upload Blog Image <b>(Minimum size approx(870px * 580px) )</b><span style="font-size:12px;color:red;">*</span></label>
        <?php echo $form->TravBlogImage;?>
       
        <label style="padding-top:5px;">Uploaded By <span style="font-size:12px;color:red;">*</span></label>
        <?php echo $form->TravUploadedBy;?>
                       
        <label style="padding-top:5px;">Upload Banner/Wall Image <b>(Minimum size approx(1600px * 300px) )</b><span style="font-size:12px;color:red;">*</span></label>
        <?php echo $form->TravBannerImage;?>
               
        <label style="padding-top:5px;">Description / Content</label>
        <?php echo $form->TravDescription;?>
        
        <label style="padding-top:5px;">Status <span style="font-size:12px;color:red;">*</span></label>
        <?php echo $form->status;?>
        
        <label style="padding-top:5px;">Tags (Enter new tags separated by | )</label>
        <?php echo $form->TravTags; ?>
        
        <label>Keyword</label>
        <?php echo $form->keyword;?>
         
        <label>Description</label>
        <?php echo $form->description;?>
          
        <label>Metatag</label>
        <?php echo $form->metatag;?>
              
        <div style="padding-top:20px;">
             <p class="msg" style="color:#ff0000;"></p>
            <input type="submit" name="save" value="Save" class="btn btn-primary">
            <button class="btn btn-primary" type="button" onclick="window.location.href='admin/travelogues/index'">Cancel</button>
        </div>
        
    </form>
      </div>
  </div>

</div>                    
    </div>
</div>
</div>
  <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css"/>
  <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>

<script type="text/javascript">
    $("#TravDate").datepicker({
//        format: "dd mm yyyy - hh:ii",
        dateFormat: 'dd/mm/yy',
        autoclose: true,
        todayBtn: true,
        startDate: "2016-01-01 10:00",
        minuteStep: 10
    });
</script>  

<script type="text/javascript">
    
   $(document).ready(function(){
        $( ".add_travelogues" ).on('submit',function(){
         
            if($('.add_travelogues input[name="TravTitle"]').val().trim() == ''){
                $('.msg').html('Please enter name');
		$('.add_travelogues input[name="TravTitle"]').focus();
                return false;
            }
            
            if($('.add_travelogues input[name="TravBlogImage"]').val().trim() == ''){
                $('.msg').html('Please enter blog image');
		$('.add_travelogues input[name="TravBlogImage"]').focus();
                return false;
            }
            

            if($('.add_travelogues select[name="TravDestination[]"]').val() === null){             
                $('.msg').html('Please select destination above');
		$('.add_travelogues select[name="TravDestination[]"]').focus();return false;
            }
            
            if($('.add_travelogues input[name="TravUploadedBy"]').val().trim() == ''){
                $('.msg').html('Please enter UploadedBy');
		$('.add_travelogues input[name="TravUploadedBy"]').focus();
                return false;
            }
            
     
            if($('.add_travelogues input[name="TravBannerImage"]').val().trim() == ''){
                $('.msg').html('Please enter banner image');
		$('.add_travelogues input[name="TravBannerImage"]').focus();
                return false;
            }
            
            if($('.add_travelogues select[name="status"]').val().trim() == ''){
                $('.msg').html('Please select status');
		$('.add_travelogues select[name="status"]').focus();
                return false;
            }
    
    });  
});
CKEDITOR.replace('TravDescription',{});
</script>
