<?php
   $options = Zend_Controller_Front::getInstance()->getParam('bootstrap')->getOption('bootstrap');
?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($options['siteName'] . " :: AdminPanel");?>
    <base href="<?php echo $options['siteUrl'];?>" />
    <script type="text/javascript">
      baseurl = '<?php echo $options['siteUrl'];?>';
    </script>
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
     <?php 
       echo $this->headLink()->prependStylesheet('public/admin/lib/bootstrap/css/bootstrap.css')
                             ->appendStylesheet('public/admin/stylesheets/theme.css')
                             ->appendStylesheet('public/admin/lib/font-awesome/css/font-awesome.css');
    ?>
    <?php
     echo $this->headScript()->prependFile('public/admin/lib/jquery-1.7.2.min.js')
                            ->appendFile('public/admin/lib/bootstrap/js/bootstrap.js');
    ?>

    <!-- Demo page code -->

    <style type="text/css">
        #line-chart {
            height:300px;
            width:800px;
            margin: 0px auto;
            margin-top: 1em;
        }
        .brand { font-family: georgia, serif; }
        .brand .first {
            color: #ccc;
            font-style: italic;
        }
        .brand .second {
            color: #fff;
            font-weight: bold;
        }
        li {list-style:none; color:#ed3237; font-size:13px;}
        ul{margin:0px; padding:0px;}
    </style>
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="../assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
  </head>

  <!--[if lt IE 7 ]> <body class="ie ie6"> <![endif]-->
  <!--[if IE 7 ]> <body class="ie ie7 "> <![endif]-->
  <!--[if IE 8 ]> <body class="ie ie8 "> <![endif]-->
  <!--[if IE 9 ]> <body class="ie ie9 "> <![endif]-->
  <!--[if (gt IE 9)|!(IE)]><!--> 
  <body class=""> 
  <!--<![endif]-->
    
    <div class="navbar">
        <div class="navbar-inner">
          <a class="brand"><span class="second"><?php echo $options['siteName']?></span></a>
        </div>
    </div>
    
<?php $form = $this->form;?>
        <div class="row-fluid">
    <div class="dialog">
        <div class="block">
            <p class="block-heading">Sign In</p>
            <div class="block-body">
                <?php if($this->errorMessage !="") { ?>
                <p style="color:red;"><?php echo $this->errorMessage;?></p>
                <?php } ?>
                <form id="login" method="<?php echo $this->form->getMethod(); ?>" name="login" action="<?php echo $this->form->getAction();?>">
                
                    <label>Username</label>
                    <?php echo $form->username;?>
                    <label>Password</label>
                     <?php echo $form->password;?>
                    
                    <label>captcha</label>
                    
                    <div> <?php echo $form->captcha;?>
                    <span align="center"  class="border-right" bgcolor="#ececec"><img src="public/captcha/captcha.php" alt="CAPTCHA code" id="captcha_one" height="50" ></span>
                    <span > <a  href="javascript:void(0);" onclick="
                        document.getElementById('captcha_one').src='public/captcha/captcha.php?'+Math.random();
                        document.getElementById('captcha').focus();"
                        id="change-image"> <img src="public/images/refresh.png" alt="Refresh image" border="0" width="16" title="Refresh" >
                     </a>                                      
                    </span>
                    </div>
                    <div class="block-body" id="dispMessage"></div>
                    <input name="submit" class="btn btn-primary pull-right" value="Sign In" type="submit">  
                    <!--<label class="remember-me"><input type="checkbox"> Remember me</label>-->
                    <div class="clearfix"></div>
                </form>
            </div>
        </div>
        <p><a href="admin/index/forgotpassword">Forgot your password?</a></p>
    </div>
</div>
    
  </body>
</html>
