<?php
$param = $this->param;
//echo "<pre>";print_r($param);die;
$contactDetail_mail = $this->contactDetail_mail;
$name = (isset($param['name']) && ($param['name']!= '')) ? $param['name'] : '';
$email = (isset($param['email']) && ($param['email']!= '')) ? $param['email'] : '';
$mobile = (isset($param['mobile']) && ($param['mobile']!= '')) ? $param['mobile'] : '';
$message_html = '';
$destination_html = '';
$querytype_html = '';
if(isset($param['message']) && ($param['message']!= '')){
    $message_html = '<tr>
    <td width="28%" style=" padding:5px 40px;vertical-align: middle;">Message : </td>
    <td width="72%" style=" padding:5px 40px;vertical-align: middle;">'.$param['message'].'</td>
  </tr>';
}

if(isset($param['destination']) && ($param['destination']!= '')){
    $destination_html = '<tr>
    <td width="28%" style=" padding:5px 40px;vertical-align: middle;">Destination : </td>
    <td width="72%" style=" padding:5px 40px;vertical-align: middle;">'.$param['destination'].'</td>
  </tr><tr>
    <td width="28%" style=" padding:5px 40px;vertical-align: middle;">Travelling From: : </td>
    <td width="72%" style=" padding:5px 40px;vertical-align: middle;">'.$param['travel_from'].'</td>
  </tr><tr>
    <td width="28%" style=" padding:5px 40px;vertical-align: middle;">Travel Date: : </td>
    <td width="72%" style=" padding:5px 40px;vertical-align: middle;">'.$param['travel_date'].'</td>
  </tr><tr>
    <td width="28%" style=" padding:5px 40px;vertical-align: middle;">No. of pax:  </td>
    <td width="72%" style=" padding:5px 40px;vertical-align: middle;">'.$param['noofpax'].'</td>
  </tr>';
}

 if(isset($param['form_type']) && (trim($param['form_type']) == 'contact_us') ){
     $querytype_html = '';
 }else{
    $querytype_html = '<tr>
    <td style=" padding:5px 40px;vertical-align: middle;">Query Type : </td>
    <td style=" padding:5px 40px;vertical-align: middle;">Package <br></td>
  </tr>';
 }
?>
<table width="60%" border="0" align="center" cellpadding="0" cellspacing="0" style=" font-size:14px; font-family: Roboto, sans-serif;">
<!--  <tr>
    <td colspan="2" align="left" style=" padding:18px 40px;vertical-align: middle;"><img src="<?php // echo $this->baseUrl;?>public/images/logo.png" /></td>
  </tr>-->
  <tr>
    <td colspan="2" style=" padding:5px 40px;vertical-align: middle;">Dear Admin, <br>
      <br>
      You have received a new travel query detail as below:</td>
  </tr>
  <tr>
    <td width="28%" style=" padding:5px 40px;vertical-align: middle;">Name : </td>
    <td width="72%" style=" padding:5px 40px;vertical-align: middle;"><?php echo $name;?></td>
  </tr>
  <tr>
    <td style=" padding:5px 40px;vertical-align: middle;">Email : </td>
    <td style=" padding:5px 40px;vertical-align: middle;"><?php echo $email;?></td>
  </tr>
  <tr>
    <td style=" padding:5px 40px;vertical-align: middle;">Phone : </td>
    <td style=" padding:5px 40px;vertical-align: middle;"><?php echo $mobile ?></td>
  </tr>
  <?php 
  echo $message_html;
  echo $destination_html;
  ?>
  
  
  <tr>
    <td colspan="2" style=" padding:5px 40px;vertical-align: middle;">Thanks ! <br>
      <hr / style="border-width: 0.6px;">
      <br>
      <?php echo $this->baseUrl;?><br>
      contact number: <?php echo$contactDetail_mail['mobile'];?><br>
      Email: <?php echo$contactDetail_mail['email'];?> </td>
  </tr>
</table>
<div style="text-align:center;">
     <img style="width:100px;" src="<?php echo $this->baseUrl;?>public/images/logo.png" />
  </div>
<table width="60%" border="0" align="center" cellpadding="0" cellspacing="0" >
<tr>
    <td style=" text-align:right;">Powered by &#45; <a  href="http://www.hellogtx.com/" target="_blank" style="font-family:AvantGarde Bk BT;color:#0b74c4; text-decoration:none">hello<span style="font-family:AvantGarde Bk BT;color:#fb5a2d;">GTX</span></a></td>
  </tr>
</table>
