<?php
$param = $this->param;
$contactDetail_mail = $this->contactDetail_mail;
//echo "<pre>";print_r($param);die;
$name = (isset($param['name']) && ($param['name']!= '')) ? $param['name'] : '';
?>
<table width="60%" border="0" align="center" cellpadding="0" cellspacing="0" style=" font-size:14px; font-family: Roboto, sans-serif;">
<!--  <tr>
    <td colspan="2" align="left" style=" padding:18px 40px;vertical-align: middle;"><img src="<?php // echo $this->baseUrl;?>public/images/logo.png" /></td>
  </tr>-->
  <tr>
    <td colspan="2" style=" padding:5px 40px;vertical-align: middle;">Dear <?php echo ucfirst($name);?>, <br>
      <br>
      Greetings from <?php echo $this->siteName;?>!  <br> <br>
      </td>
  </tr>
  <tr>
    <td colspan="2" style=" padding:5px 40px;vertical-align: middle;">Thank you for your query!</td>
  </tr>
  <tr>
    <td colspan="2" style=" padding:5px 40px;vertical-align: middle;"> We will call you as quickly as possible with best options for you.
    If you require immediate assistance, please call us on <?php echo $contactDetail_mail['mobile'];?><br><br></td>
  </tr>
  <tr>
    <td colspan="2" style=" padding:5px 40px;vertical-align: middle;"> Your opinion matters to us! We'd love to hear what you have to say about our services!<br><br>
Write in to us at email id    <?php echo $contactDetail_mail['email'];?>

</td>
  </tr>
  <tr>
    <td colspan="2" style=" padding:5px 40px;vertical-align: middle;">Thanks ! <br>
      <hr / style="border-width: 0.6px;">
      <br>
       <?php echo $this->baseUrl;?><br>
      contact number: <?php echo $contactDetail_mail['mobile'];?><br>
      Email: <?php echo $contactDetail_mail['email'];?> </td>
  </tr>
</table>
<div style="text-align:center;">
     <img style="width:100px;" src="<?php echo $this->baseUrl;?>public/images/logo.png" />
  </div>

<table width="60%" border="0" align="center" cellpadding="0" cellspacing="0" >
<tr>
    <td style=" text-align:right;">Powered by &#45; <a  href="http://www.hellogtx.com/" target="_blank" style="font-family:AvantGarde Bk BT;color:#0b74c4; text-decoration:none">hello<span style="font-family:AvantGarde Bk BT;color:#fb5a2d;">GTX</span></a></td>
  </tr>
</table>