<?php 
$options = Zend_Controller_Front::getInstance()->getParam('bootstrap')->getOption('bootstrap');
$baseUrl = $options['siteUrl'];
?>
<style type="text/css">
    li{list-style:none; color:#ed3237; font-size:13px;}
    ul{margin:0px; padding:0px;}
</style>


<div class="content">
        
<div class="header">
    <h1 class="page-title">Edit Package Page</h1>
</div>

<ul class="breadcrumb">
    <li><a href="<?php echo $options['siteUrl'];?>admin/dashboard/index">Home</a> <span class="divider">/</span></li>
    <li><a href="<?php echo $options['siteUrl'];?>admin/package/index">Manage Package Pages</a> <span class="divider">/</span></li>
    <li class="active">Edit Package Page</li>
</ul>

<div class="container-fluid">
    <div class="row-fluid">       
   
    <?php if($this->successMessage) { ?>
        <div class="alert alert-info">
        <button data-dismiss="alert" class="close" type="button">×</button>
        <?php echo $this->successMessage; ?>
        </div> 
    <?php } ?>
        
   <?php if($this->errorMessage) { ?>
       <div class="alert alert-error">
           <button data-dismiss="alert" class="close" type="button">×</button>
           <?php echo $this->errorMessage; ?>
       </div>
   <?php } ?>
      
   <?php if($this->error1Message) { ?>
       <div class="alert alert-error">
           <button data-dismiss="alert" class="close" type="button">×</button>
           <?php echo $this->error1Message; ?>
       </div>
   <?php } ?>   
        
<div class="well">
    <ul class="nav nav-tabs">
      <li class="active"><a href="#edit_page" data-toggle="tab">Edit Package Page</a></li>
    </ul>
     <?php $form = $this->form;?>
    <div id="myTabContent" class="tab-content">
      <div class="tab-pane active in" id="add_page">
    <form id="add_page" method="<?php echo $this->form->getMethod();?>" action="<?php echo $this->form->getAction();?>" name="<?php echo $this->form->getName();?>" enctype="multipart/form-data">
        <?php echo $form->sid;?>
               
        <label>Hot Deal</label>
        <?php echo $form->hot_deal;?>
        <label>Keyword's</label>
        <?php echo $form->keyword;?>
        <label>Description's</label>
        <?php echo $form->description;?>
        <label>Meta Tag</label>
        <?php echo $form->metatag;?>
        
        <label style="padding-top:5px;">Upload Image (W : 254px | H : 240px)</label>
        <input id="image" name="image[]"  autocomplete="off" multiple="multiple" class="input-xlarge" type="file">
        
        <?php 
        $imagess = explode(",", $this->image);
//        print_r($imagess); die;
        if($imagess!="") { 
            foreach($imagess as $key => $img){
                              if($key < 5) {

            ?>
        
        <img src="<?php echo $baseUrl;?>public/upload/tours/<?php echo $this->pId;?>/images/thumb/<?php echo $img;?>" border="0" alt="image" width="60" height="60" />
        
        <?php }}} ?>
        
        <div style="padding-top:20px;">
            <input type="submit" name="save" value="Save" class="btn btn-primary">
            <button class="btn btn-primary" type="button" onclick="window.location.href='admin/package/index'">Cancel</button>
        </div>
        
    </form>
      </div>
  </div>

</div>                  
    </div>
</div>
</div>