<?php 
$options = Zend_Controller_Front::getInstance()->getParam('bootstrap')->getOption('bootstrap');
$resultset = $this->resultset; 
?>
 
<div class="content">
        
<div class="header">
    <h1 class="page-title">Manage Promotion </h1>
</div>

<ul class="breadcrumb">
    <li><a href="<?php echo $options['siteUrl'];?>admin/dashboard/index">Home</a> <span class="divider">/</span></li>
    <li class="active">Manage Promotion</li>
    <li><span class="divider">/</span><a href="<?php echo $options['siteUrl'];?>admin/homepromotion/addpromotion">Add Home Promotion</a> </li>
</ul>

<div class="container-fluid">
    <div class="row-fluid">
                    

<div class="col-md-12">
    <?php if (count($this->messages)) { ?>
     <div class="alert alert-success" >
         <button data-dismiss="alert" class="close" type="button">x</button>
         <?php foreach ($this->messages as $message) {  ?>
         <?php echo $this->escape($message); ?>
         <?php } ?>
     </div>
    <?php } ?>
</div>
        
        
<div class="well">
                <table id="tt" class="easyui-datagrid" style="width:100%;" url="admin/homepromotion/index"
                       iconCls="icon-save" toolbar="#tb" rownumbers="true" pagination="true" fitColumns="true" view="scrollview" nowrap="false" >
                    <thead>
                        <tr>
                            <th field="templatetype" data-options="width:100">Template Type</th>
                            <th field="promotion_name" data-options="width:100">Promotion name</th>
                            <th field="tag_name" data-options="width:200">Tag Name</th>
                            <th data-options="field:'image',width:100,align:'center',formatter:formatImageAction">Image</th>
                            <th field="IsFeatured" data-options="width:60,align:'center',formatter:formatStatusAction">DOH</th> 
                            <th data-options="field:'firma',width:80,align:'center',formatter:formatPromotionAction">Action</th>
                            </tr>
                    </thead>
                </table>
<!--                <div id="tb" style="padding:3px;">
                    <span>Page Title:</span>
                    <input id="Title" onkeyup="doSearch()" style="line-height:26px;border: 1px solid #ccc">
                </div>-->
            </div>

</div>
    </div>
</div>

<script type="text/javascript">
    function doSearch() {
        $('#tt').datagrid('load', {
            Title: $('#Title').val(),
        });
                        }
    function formatPromotionAction(val, row) {
                            var href = 'admin/homepromotion/editpromotion/id/' + row.promotionId;
                            var hrefDel = 'admin/homepromotion/deletepromotion/id/' + row.promotionId;

                            return '<a href="' + href + '" title="Edit"><i class="icon-pencil"></i></a> &nbsp; <a href="' + hrefDel + '" onclick="return confirm(\'Are you sure you want to delete?\')" class="Delete" title="Delete"><i class="icon-trash"></i></a>';
                        }

    function formatImageAction(val, row) {
    var Image = row.promotion_image;
    if (Image !== null) {
        return '<img style="width:64px;height:50px;" src="public/upload/homepromotion/small/' + Image + '" border="0" alt="image">';

    }
    else {
        return '<img style="width:64px;height:50px;" src="public/images/icon-package.jpg" border="0">';
    }
}

    function formatStatusAction(val, row) {
            if (val != "" && val == 1) {
                var checked = "checked";
            }
            else {
                checked = "";
            }
            return '<input type="checkbox" ' + checked + ' onClick="Active(\'' + row.promotionId + '\',\'' + row.templatetypeId + '\')" id="Active_' + row.promotionId + '" name="Active" value="1">';

    }

    function Active(a,t) {

        if ($('#Active_' + a).prop("checked") === true) {
            var values = 1;
        } else if ($('#Active_' + a).prop("checked") === false) {
            values = 0;
        }
        $.ajax({
            url: '<?php echo $options['siteUrl']; ?>admin/homePromotion/active/id/' + a + '/val/' + values+ '/type/' + t,
            type: 'POST',
            dataType: 'json',
            success: function (result) {
                if (result.status) {
                    alert('Record Update successfully.');
                } else {
                 
                if (result.message === 'Limit Exceed!!') {
                alert(result.message);
                $('#Active_' + a).prop("checked", false);

                                        }
                }
            },
            error: function (result) {
                alert('Execution error activation!!');
            }
        });

    }

</script>