<?php  $url = $this->url;
if($url != ''){
?>

<html>
<head>
<meta charset="utf-8">
<meta name="author" content="">
<meta http-equiv="X-UA-Compatible" content="IE=9,10,11" />
<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1" />
<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="<?php echo Catabatic_Helper::getSiteUrl();?>public/js/jquery.responsiveiframe.js"></script>

<script type='text/javascript'>
$(function() {
  $('iframe').responsiveIframe({xdomain: '*'});
});
</script>

<style>
body {
  margin: 0;
}
</style>
</head>

<body>

<iframe src='<?php echo base64_decode($this->url); ?>' style='border:0; width: 100%; height: 100%;'></iframe>

</body>
</html>
<?php } else {
    echo "some Error";
} ?>