<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle() ?>
     <?php
        $options = Zend_Controller_Front::getInstance()->getParam('bootstrap')->getOption('bootstrap');
     ?>
    <base href="<?php echo $options['siteUrl'];?>"></base>
    <script type="text/javascript">
      baseurl = '<?php echo $options['siteUrl'];?>';
    </script>
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
     <?php 
       echo $this->headLink()->prependStylesheet('lib/bootstrap/css/bootstrap.css')
                             ->appendStylesheet('stylesheets/theme.css')
                             ->appendStylesheet('lib/font-awesome/css/font-awesome.css');
    ?>
    <?php
     echo $this->headScript()->prependFile('lib/jquery-1.7.2.min.js')
                            ->appendFile('lib/bootstrap/js/bootstrap.js');
    ?>

    <!-- Demo page code -->

    <style type="text/css">
        #line-chart {
            height:300px;
            width:800px;
            margin: 0px auto;
            margin-top: 1em;
        }
        .brand { font-family: georgia, serif; }
        .brand .first {
            color: #ccc;
            font-style: italic;
        }
        .brand .second {
            color: #fff;
            font-weight: bold;
        }
        li {list-style:none; color:#ed3237; font-size:13px;}
        ul{margin:0px; padding:0px;}
    </style>
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="../assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
  </head>

  <!--[if lt IE 7 ]> <body class="ie ie6"> <![endif]-->
  <!--[if IE 7 ]> <body class="ie ie7 "> <![endif]-->
  <!--[if IE 8 ]> <body class="ie ie8 "> <![endif]-->
  <!--[if IE 9 ]> <body class="ie ie9 "> <![endif]-->
  <!--[if (gt IE 9)|!(IE)]><!--> 
  <body class=""> 
  <!--<![endif]-->
    
    <div class="navbar">
        <div class="navbar-inner">
          <a class="brand"><span class="second">DCB BANK</span></a>
        </div>
    </div>
    
        <div class="row-fluid">
      <h1>An error occurred</h1>
      <h2><?php echo $this->message ?></h2>
      
</div>
    
  </body>
</html>