<?php // 
$options = Zend_Controller_Front::getInstance()->getParam('bootstrap')->getOption('bootstrap');
$resultset = $this->resultset; 
?>
<style type="text/css">
    li{list-style:none; color:#ed3237; font-size:13px;}
    ul{margin:0px; padding:0px;}
</style>


<div class="content">
        
<div class="header">
    <h1 class="page-title">Add Home Page Banner Details</h1>
</div>

<ul class="breadcrumb">
    <li><a href="<?php echo $options['siteUrl'];?>admin/dashboard/index">Home</a> <span class="divider">/</span></li>
    <li><a href="<?php echo $options['siteUrl'];?>admin/staticpage/home">Manage Home Page</a> <span class="divider">/</span></li>
    <li class="active">Add Home Page Banner Details</li>
</ul>

<div class="container-fluid">
    <div class="row-fluid">       
   
    <?php if($this->successMessage) { ?>
        <div class="alert alert-info">
        <button data-dismiss="alert" class="close" type="button">×</button>
        <?php echo $this->successMessage; ?>
        </div> 
    <?php } ?>
        
   <?php if($this->errorMessage) { ?>
       <div class="alert alert-error">
           <button data-dismiss="alert" class="close" type="button">×</button>
           <?php echo $this->errorMessage; ?>
       </div>
   <?php } ?>
      
   <?php if($this->error1Message) { ?>
       <div class="alert alert-error">
           <button data-dismiss="alert" class="close" type="button">×</button>
           <?php echo $this->error1Message; ?>
       </div>
   <?php } ?>   
        
<div class="well">
    <ul class="nav nav-tabs">
      <li class="active"><a href="#edit_page" data-toggle="tab">Add Home Page Banner Details</a></li>
    </ul>
     <?php $form = $this->form;?>
    <div id="myTabContent" class="tab-content">
      <div class="tab-pane active in" id="add_home">
          <form id="add_home" class="add_home" method="<?php echo $this->form->getMethod();?>" action="<?php echo $this->form->getAction();?>" name="<?php echo $this->form->getName();?>" enctype="multipart/form-data">
               
        <label>Heading</label>
        <?php echo $form->heading;?>
        <br>
        <label>Description</label>
        <?php echo $form->description;?>
        <br>
        <label>Url</label>
        <?php echo $form->url;?>
        <br>
        <br>
        <label>Open url in new tab &nbsp; <?php echo $form->opt;?></label>
        <br>
        <label style="padding-top:5px;">Upload Background Image dimensions (W :2100px | H :796px)</label>
        <?php echo $form->image;?>
        
        <label style="padding-top:10px;">Status</label>
        <?php echo $form->status;?>
        
         
        <div style="padding-top:20px;">
            <p class="msg" style="color:#ff0000;"></p>
            <input type="submit" name="save" value="Save" class="btn btn-primary">
            <button class="btn btn-primary" type="button" onclick="window.location.href='admin/staticpage/home'">Cancel</button>
        </div>
        
    </form>
      </div>
  </div>

</div>                    
    </div>
</div>
</div>

<script type="text/javascript">
CKEDITOR.replace('description',{});

$(document).ready(function(){
  $(".option").click(function(){
     var urlType = $("input[name='opt[]']:checked").length;
     if(urlType > 1){
         alert("Can't select more than one");
         return false;
     }
  });
  
  
});

</script>