<?php
$options = Zend_Controller_Front::getInstance()->getParam('bootstrap')->getOption('bootstrap');
$resultset = $this->resultset;
?>

<div class="content">

    <div class="header">
        <h1 class="page-title">Manage Home Page</h1>
    </div>

    <ul class="breadcrumb">
        <li><a href="<?php echo $options['siteUrl']; ?>admin/dashboard/index">Home</a> <span class="divider">/</span></li>
        <li class="active">Manage Home Page <span class="divider">/</span></li>
        <li><a href="<?php echo $options['siteUrl']; ?>admin/staticpage/addhome">Add Home Page Banner Details</a> </li>
    </ul>

    <div class="container-fluid">
        <div class="row-fluid">


            <div class="col-md-12">
                <?php if (count($this->messages)) { ?>
                    <div class="alert alert-success" >
                        <button data-dismiss="alert" class="close" type="button">x</button>
                        <?php foreach ($this->messages as $message) { ?>
                            <?php echo $this->escape($message); ?>
                        <?php } ?>
                    </div>
                <?php } ?>
            </div>


            <div class="well">
                <table id="tt" class="easyui-datagrid" style="width:100%;" url="admin/staticpage/home"
                       iconCls="icon-save" toolbar="#tb" rownumbers="true" pagination="true" fitColumns="true" view="scrollview" nowrap="false" >
                    <thead>
                        <tr>
                            <th field="heading" data-options="width:100">Heading</th>
                            <th field="description" data-options="width:100">Description</th>
                            <th data-options="field:'image',width:300,align:'center',formatter:formatBannerImageAction">Image</th>
                            <th field="isDisplayOnHome" data-options="width:100,align:'center',formatter:formatStatusAction">DOH</th>
                            <th data-options="field:'firma1',width:80,align:'center',formatter:formatHomeAction">Action</th>
                        </tr>
                    </thead>
                </table>                
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    function formatHomeAction(val, row) {
        var href = 'admin/staticpage/edithome/id/' + row.banner_id;
        var hrefDel = 'admin/staticpage/deletehome/id/' + row.banner_id;
        return '<a href="' + href + '" title="Edit"><i class="icon-pencil"></i></a> &nbsp; <a href="' + hrefDel + '" onclick="return confirm(\'Are you sure you want to delete?\')" class="Delete" title="Delete"><i class="icon-trash"></i></a>';
    }

    function formatBannerImageAction(val, row) {
        var Bannerimg = row.image;
        if (Bannerimg !== null) {
            return '<img src="public/upload/home/' + row.banner_id + '/' + Bannerimg + '" style="width:176px;height:51px;" border="0" alt="banner image">&nbsp;&nbsp;<a href="javascript:void(0)" onclick="deleteImage(\'' + row.banner_id + '\',\'' + Bannerimg + '\')" title="Delete Image"><i class="fa fa-times"></i>x</a>';
            ;
        }
        else {
            return '<img src="public/images/icon-package.jpg" style="width:176px;height:51px;" border="0" alt="No image" id="image_id_' + row.banner_id + '" width="64">';
        }
    }
    function formatStatusAction(val, row) {
        if (val != "" && val == 1) {
            var checked = "checked";
        }
        else {
            checked = "";
        }
        return '<input type="checkbox" ' + checked + ' onClick="Active(\'' + row.banner_id + '\')" id="Active_' + row.banner_id + '" name="Active" value="1">';

    }

    function Active(a) {

        if ($('#Active_' + a).prop("checked") === true) {
            var values = 1;
        } else if ($('#Active_' + a).prop("checked") === false) {
            values = 0;
        }
        $.ajax({
            url: '<?php echo $options['siteUrl']; ?>admin/staticpage/active/id/' + a + '/val/' + values,
            type: 'POST',
            dataType: 'json',
            success: function (result) {
                if (result.status) {
                    alert('Record Update successfully.');
                } else {
                    alert(result.message);
                }
            },
            error: function (result) {
                alert('Execution error activation!!');
            }
        });

    }

    function deleteImage(id, images) {

        if (!confirm('Are you sure you want to delete?')) {
            return false;
        } else {
            $.ajax({
                url: "<?php echo $baseUrl; ?>admin/staticpage/deleteimage?id=" + id + "&images=" + images,
                type: "POST",
                data: '',
                dataType: "json",
                success: function (response) {
//                alert(response.msg);
                    window.location.href = "<?php echo $baseUrl; ?>admin/staticpage/home";
                    //           $(this).parent().prev().remove();
                },
            });
        }
    }
</script>