<?php
$options = Zend_Controller_Front::getInstance()->getParam('bootstrap')->getOption('bootstrap');
$baseUrl    = $this->baseUrl;
$apiData    = $this->apiData;
//echo '<pre>';print_r($apiData);die('ppp');
?>
<style>
    input:focus,
    input:active {
    border: 1px solid red;
}
</style>

<div class="search-result">
    <div class="overlay">
      <div class="box">
        <div class="container">
        <div class="col-md-12 ">
          <div class="animate-box " data-animate-effect="fadeIn">
            <h1>Continue Login</h1>
            <ol class="breadcrumb">
              <li><a href="index.html" class="link home">Home</a></li>
              <li class="active"><a href="#" class="link">Login</a></li>
            </ol>
          </div>
        </div>
        </div>
        
      </div>
    </div>
    <img src="/public/images/user-profile.jpg" alt="" title="" class="img-mobile-responsive"></div>
    
    <div id="fh5co-blog" class="fh5co-section fh5co-hand about-section">
  <div class="container">
      <section style=" padding:0;">
                <div class="row" style="margin:0;">  
                  <div class="col-md-12 col-sm-12 alert alert-gray-light profile_Count">
                  <div class="mt-3"></div>
                  
                  <div class="mt-3"></div>
                  
                   <div class="content">
                        <form id="continue_login" method="POST" action="login"> 
                            <div class="row">

                                <div class="col-md-12">
                                    <div style="text-align: center; padding: 30px;">
                                        <img src="<?php echo $this->baseUrl('public/images/loader.gif'); ?>">
                                        <h2 style="font-size: 12px;">[ Please wait we are redirecting you. Please do not refresh or press back button, We are Processing Your login... ]</h2>
                                    </div>
                                    <p style="color:red;text-align: center;" class="signuperror_msg"></p>
                                    <p style="color:green;text-align: center;" class="signupsuccess_msg"></p>
                                </div>

                            </div>


                            <div class="clearfix"></div>
                        </form>
                    </div>
                  </div>
                  
                  <div class="cl"></div>
                </div>
                
              </section>
    
    </div>
    <div class="clearfix"></div>
  </div>

