<?php
$options = Zend_Controller_Front::getInstance()->getParam('bootstrap')->getOption('bootstrap');
$baseUrl = $this->baseUrl;
?>
<style>
    input:focus,
    input:active {
        border: 1px solid red;
    }
</style>

<div id="content" class="site-content">
    <div id="tropical-banner" class=" text-center clearfix">
        <img src="<?php echo $baseUrl; ?>public/images/central/static-theme-images.jpg" alt="banner" style="height: 320px;width: 1349px;"/>
        <div class="container banner-contents clearfix">
            <h2 class="template-title p-name"><strong>PROFILE</strong></h2>

        </div>
        <div class="breadcrumb-wrapper clearfix">
            <div class="container">
                <ol class="breadcrumb">
                    <li><a href="<?php echo $baseUrl; ?>" >Home</a></li>
                    <li class="active">Profile</li>
                </ol>
            </div>
        </div>
        <span class="overlay"></span>
    </div>
    <section class="contact-template clearfix">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12">
                    <article class="blog-post">

                        <div class="col-md-12">
                            <h3>Profile</h3>
                            <ul class="demo" style="padding-top:0; display: inherit !important; ">
                                <li><a> My Profile</a>
                                    <section style=" padding:0;">
                                        <div class="row" style="margin:0;">
                                            <div class="col-md-12 col-sm-12 alert alert-gray-light profile_Count">
                                                <div class="mt-3"></div>
                                                <!--<h1 class="no-margin mt-headimg">My Profile</h1>-->
                                                <div class="mt-3"></div>
                                                <div class="content">
                                                    <form id="update_profile" method="POST" action="updateprofile">
                                                        <div class="row">
                                                            <div class="col-md-3">
                                                                <div class="form-group">
                                                                    <label>Title </label>
                                                                    <select name="title" class="form-control border-input" placeholder="Select">
                                                                        <?php if ($this->salutation) {
                                                                            foreach ($this->salutation as $key => $title) {
                                                                                ?>
                                                                                <option value="<?php echo $key; ?>" <?php echo (!empty($this->profile['Title']) && $key == $this->profile['Title']) ? 'selected="selected"' : 'NA' ?>><?php echo $title; ?></option>
                                                                            <?php }
                                                                        }
                                                                        ?>
                                                                    </select>
                                                                </div>
                                                            </div>
                                                            <div class="col-md-3">
                                                                <div class="form-group">
                                                                    <label>First name</label> <span style="color:red">*</span>
                                                                    <input class="form-control border-input" name="FirstName" value="<?php echo trim($this->profile['FirstName']); ?>" type="text">
                                                                </div>
                                                            </div>
                                                            <div class="col-md-3">
                                                                <div class="form-group">
                                                                    <label for="exampleInputEmail1">Last name</label> <span style="color:red">*</span>
                                                                    <input class="form-control border-input" name="LastName" value="<?php echo trim($this->profile['LastName']); ?>" type="text">
                                                                </div>
                                                            </div>
                                                            <div class="col-md-3">
                                                                <div class="form-group">
                                                                    <label for="exampleInputEmail1">Mobile</label> <span style="color:red">*</span>
                                                                    <input class="form-control border-input" name="contacts" value="<?php echo trim($this->profile['Contacts']); ?>" type="text">
                                                                </div>
                                                            </div>
                                                        </div>

                                                        <div class="row">
                                                            <div class="col-md-3">
                                                                <div class="form-group">
                                                                    <label>Email</label> <span style="color:red">*</span>
                                                                    <input class="form-control border-input" name="EmailId" disabled="disabled" value="<?php echo $this->profile['EmailId']; ?>" type="text">
                                                                </div>
                                                            </div>
                                                            <div class="col-md-3">
                                                                <div class="form-group">
                                                                    <label>Country</label> <span style="color:red">*</span>
                                                                    <select id="select-country" name="country" onchange="populateCity(this);" cityData ="<?php echo $this->profile['CitySysId']; ?>" class="form-control border-input" placeholder="Select">
                                                                        <option value="">Select</option>
                                                                        <?php if ($this->countryArr) {
                                                                            foreach ($this->countryArr as $country) { ?>
                                                                                <option value="<?php echo $country['ContId'] ?>" <?php echo (!empty($this->profile['CountrySysId']) && $country['ContId'] == $this->profile['CountrySysId']) ? 'selected="selected"' : 'NA' ?>><?php echo $country['Title'] ?></option>
                                                                            <?php }
                                                                        } ?>
                                                                    </select>                        
                                                                </div>
                                                            </div>
                                                            <div class="col-md-3">
                                                                <div class="form-group">
                                                                    <label>City</label> <span style="color:red">*</span>
                                                                    <input type="hidden" id="city_id" name="city_id" value="<?php echo $this->profile['CitySysId']; ?>">
                                                                    <select id="select-city" name="city" class="form-control border-input" placeholder="Select">

                                                                    </select>                        
                                                                </div>
                                                            </div>

                                                            <div class="col-md-3">
                                                                <div class="form-group">
                                                                    <label>Passport No.</label>
                                                                    <input class="form-control border-input" name="PassportNo" value="<?php echo!empty($this->profile['PassportNo']) ? $this->profile['PassportNo'] : '' ?>" type="text">
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="row">
                                                            <div class="col-md-3">
                                                                <div class="form-group">
                                                                    <label>Passport Expiry</label>
                                                                    <input class="form-control border-input Passdatepicket" name="PassportExpiry" value="<?php echo ($this->profile['PassportExpiry'] !== '01/01/1900') ? $this->profile['PassportExpiry'] : ''; ?>" id="J-demo-01" type="text">
                                                                </div>
                                                            </div>
                                                            <div class="col-md-3">
                                                                <div class="form-group">
                                                                    <label>DOB</label>
                                                                    <input class="form-control border-input dateofbirth" name="DOB"  placeholder="" value="<?php echo ($this->profile['DOB'] !== '01/01/1900') ? $this->profile['DOB'] : ''; ?>" id="J-demo-02" type="text">
                                                                </div>
                                                            </div>
                                                            <div class="col-md-3">
                                                                <div class="form-group">
                                                                    <label>Marriage Anniversary</label>
                                                                    <input class="form-control border-input MarriageAnniversary"  name="MarriageAnniversary" placeholder="" value="<?php echo ($this->profile['MarriageAnniversary'] !== '01/01/1900') ? $this->profile['MarriageAnniversary'] : ''; ?>" id="J-demo-03" type="text">
                                                                </div>
                                                            </div>

                                                            <div class="col-md-3">
                                                                <div class="text-left" style="margin-top:37px;">
                                                                    <button type="submit" class="btn btn-danger change">Update Profile</button>
                                                                    
                                                                </div>
                                                                <div class="mt-btn-form"></div>
                                                            </div>
                                                        </div>
                                                        <div class="clearfix"></div>
                                                    </form>
                                                </div>
                                            </div>
                                            <div class="cl"></div>
                                        </div>
                                    </section>
                                </li>
<!--                                <li><a>My Trips </a>
                                    <section style=" padding:0;">
                                        <div class="row" style="margin:0;">
                                            <div class="col-md-12 col-sm-12 alert alert-gray-light profile_Count">
                                                <div class="mt-3"></div>
                                                <h1 class="no-margin mt-headimg">My Trips </h1>
                                                <div class="mt-3"></div>
                                                <div class="content table-responsive table-full-width">
                                                    <table class="table1 table-striped">
                                                        <thead>
                                                            <tr>
                                                                <th>Proposal ID</th>
                                                                <th>Booking Date</th>
                                                                <th>Flight No.</th>
                                                                <th>Booking Id / PNR No.</th>
                                                                <th>Origin / Destination</th>
                                                                <th>Dep. Date Time</th>
                                                                <th>Amount</th>
                                                                <th>Status</th>
                                                                <th>Customer Name</th>
                                                                <th>Action</th>
                                                        </thead>
                                                        <tbody>
                                                            <tr>
                                                                <td>1</td>
                                                                <td>D/17/11550/V1</td>
                                                                <td>Paro,Thimphu</td>
                                                                <td>20/06/2017</td>
                                                                <td>2 Adult(s)</td>
                                                                <td>Package</td>
                                                                <td>50,000</td>
                                                                <td>9810729138</td>
                                                                <td>Confirmed</td>
                                                                <td><a href="#">View</a></td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                            <div class="cl"></div>
                                        </div>
                                    </section>
                                </li>-->
                                <li><a>Change Password</a>
                                    <section style=" padding:0;">
                                        <div class="row" style="margin:0;">
                                            <div class="col-md-12 col-sm-12 alert alert-gray-light profile_Count">
                                                <div class="mt-3"></div>
                                                <!--<h1 class="no-margin mt-headimg">Change Password</h1>-->
                                                <div class="mt-3"></div>
                                                <div class="content">
                                                    <form id="change_password" method="POST" action="changepassword">
                                                        <div class="row">
                                                            <div class="col-md-3">
                                                                <div class="form-group">
                                                                    <label>Old Password </label>
                                                                    <input class="form-control border-input" name="cpass" type="password">
                                                                </div>
                                                            </div>

                                                            <div class="col-md-3">
                                                                <div class="form-group">
                                                                    <label>New Password</label>
                                                                    <input class="form-control border-input" name="npass" type="password">
                                                                </div>
                                                            </div>

                                                            <div class="col-md-3">
                                                                <div class="form-group">
                                                                    <label>Confirm Password</label>
                                                                    <input class="form-control border-input" name="copass" type="password">
                                                                </div>
                                                            </div>

                                                            <div class="col-md-3">
                                                                <div class="text-left" style="margin-top:37px;">

                                                                    <button type="submit" class="btn btn-danger change">Update</button>
                                                                    
                                                                    <div class="mt-btn-form"></div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="clearfix"></div>
                                                    </form>
                                                </div>
                                            </div>
                                            <div class="cl"></div>
                                        </div>
                                    </section>
                                </li>
                                <span style="color:red;padding-left: 30px;font-size: 16px;" class="alrt_msg"></span><span style="color:green;padding-left: 30px;font-size: 16px;" class="alrt_msg_success"></span><span class="passchange_msg"></span>
                            </ul>
                        </div> 
                        <div class="clearfix"></div> 
                    </article>
                </div>
            </div>
        </div>
    </section>
</div>