<?php
$options = Zend_Controller_Front::getInstance()->getParam('bootstrap')->getOption('bootstrap');
$baseUrl    = $this->baseUrl;
//echo $this->action;die;
?>
<style>
    input:focus,
    input:active {
    border: 1px solid red;
}
</style>
    
<div id="content" class="site-content">
    <div id="tropical-banner" class=" text-center clearfix">
        <img src="<?php echo $baseUrl; ?>public/images/central/static-theme-images.jpg" alt="banner" style="height:320px;width: 1349px;"/>
        <div class="container banner-contents clearfix">
            <h2 class="template-title p-name"><strong>CHANGE PASSWORD</strong></h2>

        </div>
        <div class="breadcrumb-wrapper clearfix">
            <div class="container">
                <ol class="breadcrumb">
                    <li><a href="<?php $baseUrl; ?>" >Home</a></li>
                    <li class="active">CHANGE PASSWORD</li>
                </ol>
            </div>
        </div>
        <span class="overlay"></span>
    </div>
      <section style=" padding:0;">
                <div class="row" style="margin:0;">  
                  <div class="col-md-12 col-sm-12 alert alert-gray-light profile_Count">
                  <div class="mt-3"></div>
                  <h1 class="no-margin mt-headimg">Change Password</h1>
                  <div class="col-md-12">&nbsp;</div>
                  <div class="col-md-12">
                                    <p style="color:red;" class="passchange_msg"></p>
                                </div>
                   <div class="content">
                        <form id="reset_password" method="POST" action="resetpassword"> 
                            <div class="row">
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>New Password </label>
                                        <input class="form-control border-input" name="npass" type="password">
                                    </div>
                                </div>

                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Confirm Password</label>
                                        <input class="form-control border-input" name="copass" type="password">
                                    </div>
                                </div>

                                
                                <div class="col-md-3">
                                    <div class="text-left" style="margin-top:27px;">

                                        <button type="submit" class="btn btn-danger change">Submit</button>

                                        <div class="mt-btn-form"></div>
                                    </div>
                                </div>
                                

                            </div>


                            <div class="clearfix"></div>
                        </form>
                    </div>
                  </div>
                  
                  <div class="cl"></div>
                </div>
                
              </section>
    
    </div>