<?php 
$options = Zend_Controller_Front::getInstance()->getParam('bootstrap')->getOption('bootstrap');
?>

<!--banner start here-->
<div id="content" class="site-content">
    <div class="main-slider-wrap">
      <div class="main-slider">          
        <div class="item"> <img style="width:1349px;height:440px;" src="<?php echo $options['siteUrl']; ?>public/images/error_404_http_code.jpg" alt="one" />
        </div>
      </div>
    </div>
    </div>
<!--banner end here-->