<?php 
$options = Zend_Controller_Front::getInstance()->getParam('bootstrap')->getOption('bootstrap');
?>
<style>
li {list-style:none; color:#ed3237; font-size:13px;}
ul{margin:0px; padding:0px;}
</style>

<div class="content">
        
<div class="header">
    <h1 class="page-title">Change Password</h1>
</div>

<ul class="breadcrumb">
    <li><a href="<?php echo $options['siteUrl'];?>admin/dashboard/index">Home</a> <span class="divider">/</span></li>
    <li class="active">Settings <span class="divider">/</span></li>
    <li class="active">Change Password</li>
</ul>

<div class="container-fluid">
    <div class="row-fluid">
        
        <?php if($this->successMessage) { ?>
        <div class="alert alert-info">
            <button data-dismiss="alert" class="close" type="button">×</button>
            <?php echo $this->successMessage;?>
        </div>	
        <?php } ?>
		
        <?php if($this->errorMessage) { ?>
        <div class="alert alert-error">
            <button data-dismiss="alert" class="close" type="button">×</button>
            <?php echo $this->errorMessage;?>
        </div>
        <?php } ?>
                    
<div class="well">
    <ul class="nav nav-tabs">
      <li class="active"><a href="#changepassword" data-toggle="tab">Change Password</a></li>
    </ul>
    <?php $form = $this->form;?>
    <div id="myTabContent" class="tab-content">
    <div class="tab-pane active in" id="changepassword">
        <form id="tab" method="<?php echo $this->form->getMethod(); ?>" action="<?php echo $this->form->getAction(); ?>">
            <label>Current Password</label>
            <?php echo $form->old_pass;?>
            <label>New Password</label>
            <?php echo $form->password;?>
            <label>Confirm Password</label>
            <?php echo $form->cpassword;?>
            <div> <button class="btn btn-primary" type="submit">Submit</button> </div>
        </form>
    </div>
  </div>

</div>
                                 
    </div>
</div>
</div>