<?php
$items = $this->items;
?>
<div class="content">
        
<div class="header">
    <h1 class="page-title">Dashboard</h1>
</div>

<ul class="breadcrumb">
    <li><a href="admin/dashboard/index">Home</a> <span class="divider">/</span></li>
    <li class="active">Dashboard</li>
</ul>

<div class="container-fluid">
    

    <div class="row-fluid">
                    
<div class="row-fluid">

    <div class="block">
        <a href="#page-stats" class="block-heading" data-toggle="collapse">Latest Stats</a>
        <div id="page-stats" class="block-body collapse in">

            <div class="stat-widget-container">
                <div class="stat-widget">
                    <div class="stat-button">
                        <i class="icon-icloud"></i>
                        <p class="title"><?php echo $items['destination']?></p>
                        <p class="detail">Destination(s)</p>
                    </div>
                </div>

                <div class="stat-widget">
                    <div class="stat-button">
                        <p class="title"><?php echo $items['package']?></p>
                        <p class="detail">Package(s)</p>
                    </div>
                </div>

<!--                <div class="stat-widget">
                    <div class="stat-button">
                        <p class="title"><?php echo $items['hotel']?></p>
                        <p class="detail">Hotel(s)</p>
                    </div>
                </div>

                <div class="stat-widget">
                    <div class="stat-button">
                        <p class="title"><?php echo $items['activity']?></p>
                        <p class="detail">Activity(s)</p>
                    </div>
                </div>-->

            </div>
        </div>
    </div>
</div>

        
    </div>

</div>
    
    
    
</div>