<div class="col-md-3 col-sm-4">
                        <aside class="sidebar">
                            <section class="search-widget animatedParent">
                                <h5 class="hidden animated fadeInDownShort">Title</h5>
                                
                            </section>
                            <section class="widget recent-post-widget animatedParent">
                                <h5 class="widget-title animated fadeInDownShort">Recent Blog Post</h5>
                                <article class="post blog-post-widget clearfix animated fadeInUpShort">
                                    <figure class="blog-feature-img pull-right">
                                        <img src="<?php echo $baseUrl; ?>public/images/blog-post-widget-img-min.jpg" alt="Blog Image"/>
                                    </figure>
                                    <h6 class="title"><a href="#">the standard blog post title</a></h6>
                                    <time datetime="2007-08-29T13:58Z"  class="post-meta"><i class="fa fa-clock-o"></i> 08 Nov @014</time>
                                </article>
                                <article class="post blog-post-widget clearfix animated fadeInUpShort">
                                    <figure class="blog-feature-img pull-right">
                                        <img src="<?php echo $baseUrl; ?>public/images/blog-post-widget-img-min.jpg" alt="Blog Image"/>
                                    </figure>
                                    <h6 class="title"><a href="#">the standard blog post title</a></h6>
                                    <time datetime="2007-08-29T13:58Z"  class="post-meta"><i class="fa fa-clock-o"></i> 08 Nov @014</time>
                                </article>
                                <article class="post blog-post-widget clearfix animated fadeInUpShort">
                                    <figure class="blog-feature-img pull-right">
                                        <img src="<?php echo $baseUrl; ?>public/images/blog-post-widget-img-min.jpg" alt="Blog Image"/>
                                    </figure>
                                    <h6 class="title"><a href="#">the standard blog post title</a></h6>
                                    <time datetime="2007-08-29T13:58Z"  class="post-meta"><i class="fa fa-clock-o"></i> 08 Nov @014</time>
                                </article>
                            </section>
<!--                            <section class="widget widget-text animatedParent">
                                <h5 class="widget-title animated fadeInDownShort">about us</h5>
                                <p class="animated fadeInUpShort">  voluptatem accusantium doloremque laudantium, totam rem aperiam eaqu ipsa quae ab illo inventore veritatis et quasi archit ecto beatae vitae dicta sunt explicabo.
                        <a href="#">+ More...</a>         
                                 </p>
                            </section>-->
<!--                            <section class="widget contact-widget clearfix animatedParent">
                                <h5 class="widget-title animated fadeInDownShort">Contact us</h5>
                                <address class="animated fadeInUpShort">
                                    <strong> Address:</strong> Central Asia Guided Tours Pvt.Ltd, B-48b, First Floor, Kalkaji New Delhi-110019                                 </address>
                                <p class="phone-number animated fadeInUpShort"><strong>Phone:</strong> +91-11-41827910/20 </p>
                                <p class="phone-number animated fadeInUpShort"><strong>Mobile:</strong> +91-9810443944  </p>
                                <p class="email animated fadeInUpShort"><strong>Email:</strong> cagtpl@gmail.com / info@centralasiaguidedtours.com </p>
                                <ul class="social-nav text-center clearfix animated fadeInUpShort">
                                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                    <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                                    <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                                    <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                                </ul>
                            </section>-->
                        </aside>
                    </div>