<?php 
$options = Zend_Controller_Front::getInstance()->getParam('bootstrap')->getOption('bootstrap');
?>
<style type="text/css">
    li{list-style:none; color:#ed3237; font-size:13px;}
    ul{margin:0px; padding:0px;}
</style>
<?php
echo $this->headScript()->prependFile($options['siteUrl'].'public/fckeditor/fckeditor.js',$type='text/javascript'); ?>
<script type="text/javascript">
window.onload = function()
{
    if(document.getElementById('page_description')) {
        var oFCKeditor = new FCKeditor('page_description') ;
        oFCKeditor.BasePath = "public/fckeditor/" ;
        oFCKeditor.Height = 400;
        oFCKeditor.Width = 600; 
        oFCKeditor.ReplaceTextarea();
    }
}
</script>

<div class="content">
        
<div class="header">
    <h1 class="page-title">Edit Explore Links</h1>
</div>

<ul class="breadcrumb">
    <li><a href="<?php echo $options['siteUrl'];?>admin/dashboard/index">Home</a> <span class="divider">/</span></li>
    <li><a href="<?php echo $options['siteUrl'];?>admin/recommendation/index">Manage Recommendation Links</a> <span class="divider">/</span></li>
    <li class="active">Edit Recommendation Links</li>
</ul>

<div class="container-fluid">
    <div class="row-fluid">       
   
    <?php if($this->successMessage) { ?>
        <div class="alert alert-info">
        <button data-dismiss="alert" class="close" type="button">×</button>
        <?php echo $this->successMessage; ?>
        </div> 
    <?php } ?>
        
   <?php if($this->errorMessage) { ?>
       <div class="alert alert-error">
           <button data-dismiss="alert" class="close" type="button">×</button>
           <?php echo $this->errorMessage; ?>
       </div>
   <?php } ?>
      
   <?php if($this->error1Message) { ?>
       <div class="alert alert-error">
           <button data-dismiss="alert" class="close" type="button">×</button>
           <?php echo $this->error1Message; ?>
       </div>
   <?php } ?>   
        
<div class="well">
    <ul class="nav nav-tabs">
      <li class="active"><a href="#edit_page" data-toggle="tab">Edit Social Page</a></li>
    </ul>
     <?php $form = $this->form;?>
    <div id="myTabContent" class="tab-content">
      <div class="tab-pane active in" id="add_page">
    <form id="add_page" method="<?php echo $this->form->getMethod();?>" action="<?php echo $this->form->getAction();?>" name="<?php echo $this->form->getName();?>" enctype="multipart/form-data">
        <?php echo $form->id;?>
               
        <label>Name</label>
        <?php echo $form->title;?>
       
        <label>Full Url</label>
        <?php echo $form->url;?>
        
       <label>Open Type</label>
        <?php echo $form->open_link;?>
        
        
        <label>Status</label>
        <?php echo $form->status_number;?>
        
        
        
        <div style="padding-top:20px;">
            <input type="submit" name="save" value="Save" class="btn btn-primary">
            <button class="btn btn-primary" type="button" onclick="window.location.href='admin/recommendation/index'">Cancel</button>
        </div>
        
    </form>
      </div>
  </div>

</div>                    
    </div>
</div>
</div>