<?php 
$options = Zend_Controller_Front::getInstance()->getParam('bootstrap')->getOption('bootstrap');
$baseUrl = $options['siteUrl'];
?>
<style type="text/css">
    li{list-style:none; color:#ed3237; font-size:13px;}
    ul{margin:0px; padding:0px;}
</style>
 

<div class="content">

<div class="header">
    <h1 class="page-title">Edit Destination Region For Header</h1>
</div>

<ul class="breadcrumb">
    <li><a href="<?php echo $options['siteUrl'];?>admin/dashboard/index">Home</a> <span class="divider">/</span></li>
    <li><a href="<?php echo $options['siteUrl'];?>admin/destination/region">Manage Destination Region List For Header</a> <span class="divider">/</span></li>
    <li class="active">Edit Region For Header</li>
</ul>

<div class="container-fluid">
    <div class="row-fluid">       
   
    <?php if($this->successMessage) { ?>
        <div class="alert alert-info">
        <button data-dismiss="alert" class="close" type="button">×</button>
        <?php echo $this->successMessage; ?>
        </div> 
    <?php } ?>
        
   <?php if($this->errorMessage) { ?>
       <div class="alert alert-error">
           <button data-dismiss="alert" class="close" type="button">×</button>
           <?php echo $this->errorMessage; ?>
       </div>
   <?php } ?>
      
   <?php if($this->error1Message) { ?>
       <div class="alert alert-error">
           <button data-dismiss="alert" class="close" type="button">×</button>
           <?php echo $this->error1Message; ?>
       </div>
   <?php } ?>   
        
<div class="well">
    <ul class="nav nav-tabs">
      <li class="active"><a href="#edit_page" data-toggle="tab">Edit Region For Header</a></li>
    </ul>
     <?php $form = $this->form;?>
    <div id="myTabContent" class="tab-content">
      <div class="tab-pane active in" id="add_page">
    <form id="add_page" method="<?php echo $this->form->getMethod();?>" action="<?php echo $this->form->getAction();?>" name="<?php echo $this->form->getName();?>" enctype="multipart/form-data">
        <?php echo $form->sid;?>
               
        <label>Title</label>
        <?php echo $form->title;?>
        
        <label>Image (Size must be approx W:120px; H:233px)</label>
        <?php echo $form->image;?>
         <?php if($this->image!="") { ?>
        <img src="public/upload/region/small/<?php echo $this->image;?>" border="0" alt="image" width="40" height="40">
        <?php } ?>
        <label>Status</label>
        <?php echo $form->status;?>
        
        
        <div style="padding-top:20px;">
            <input type="submit" name="save" value="Save" class="btn btn-primary">
            <button class="btn btn-primary" type="button" onclick="window.location.href='admin/destination/region'">Cancel</button>
        </div>
        
    </form>
      </div>
  </div>

</div>                    
    </div>
</div>
</div>